// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!\n");

Console.ForegroundColor = ConsoleColor.DarkRed;

Console.WriteLine("==========================================\n");
Console.ResetColor();

Console.WriteLine("");

Console.ForegroundColor = ConsoleColor.DarkGreen;

Console.WriteLine("**Welcome to a game called Numbers***\n");
Console.WriteLine("Your task is to guess what number will be generated by a random generator called RANMASS.\n");
Console.WriteLine("Rule 1: The possible numbers will be between 1 and 10\n");
Console.WriteLine("Rule 2: You have 3 guesses\n");

Console.WriteLine("==========================================\n");

Console.ForegroundColor = ConsoleColor.Blue;

Console.WriteLine("PRESS ANY KEY TO START\n");
Console.ReadKey();

var randomLuckyGeneratorNumber = new Random().Next(1, 11); //RANMASS Generator

Console.WriteLine("Guess any whole number between 1 and 10.\n");

var numberGuessed = 0;
var allowedGuesses = 3;
var numberOfTries = 0;


while (numberOfTries < allowedGuesses) //when numberOfTries < 3
{
    int.TryParse(Console.ReadLine(), out numberGuessed);
    numberOfTries++;

    if (numberGuessed == randomLuckyGeneratorNumber) //If the correct number is guessed
    {
        Console.WriteLine($"Congatulations! You have guessed the correct number {randomLuckyGeneratorNumber}.\n");
        break;
    }
    else if (numberGuessed < randomLuckyGeneratorNumber && numberOfTries != 3)
    {
        Console.WriteLine("Bad luck, here's a hint, try a HIGHER number\n");
    }
    else if (numberGuessed > randomLuckyGeneratorNumber && numberOfTries != 3)
    {
        Console.WriteLine("Bad luck, here's a hint, try a LOWER number\n");
    }

    var triesLeft = (allowedGuesses - numberOfTries);
    
    if (triesLeft == 0)
    {
        Console.ForegroundColor = ConsoleColor.Red;
        Console.WriteLine("Too bad, you have zero tries left, see ya!\n"); //If no more tries left
        break;
    }
    else if (triesLeft == 1) 
    {
        Console.WriteLine($"Don't give up, you have {triesLeft} try left.\n");  //Singular try left
    }
    else
    {
        Console.WriteLine($"Don't give up, you have {triesLeft} tries left.\n"); //Pural try left
    }
    
}


