// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!\n");

Console.ForegroundColor = ConsoleColor.DarkRed;

Console.WriteLine("==========================================\n");
Console.ResetColor();

Console.WriteLine("");

Console.ForegroundColor = ConsoleColor.DarkGreen;

Console.WriteLine("**Welcome to a game called Numbers***\n");
Console.WriteLine("Your task is to guess what number will be generated by a random generator called RANMASS.\n");
Console.WriteLine("Rule 1: The possible numbers will be between 1 and 10.\n");
Console.WriteLine("Rule 2: You have infinite guesses until you guess the correct number.\n");

Console.WriteLine("==========================================\n");

Console.ForegroundColor = ConsoleColor.Blue;

Console.WriteLine("PRESS ANY KEY TO START\n");
Console.ReadKey();

var randomLuckyGeneratorNumber = new Random().Next(1, 11); //RANMASS Generator

Console.WriteLine("Guess any whole number between 1 and 10.\n");

var numberGuessed = 0;

while (numberGuessed != randomLuckyGeneratorNumber)//Setting up infinite loop
{
    int.TryParse(Console.ReadLine(), out numberGuessed);

    if (numberGuessed == randomLuckyGeneratorNumber) //If correct number is guessed leave loop via break
    {
        Console.ForegroundColor = ConsoleColor.Red;
        Console.WriteLine($"Congatulations! You have guessed the correct number {randomLuckyGeneratorNumber}.\n");
        break;
    }
    else if (numberGuessed < randomLuckyGeneratorNumber)
    {
        Console.WriteLine("Bad luck, here's a hint, try a HIGHER number\n"); //If wrong guess give user hint
    }
    else if (numberGuessed > randomLuckyGeneratorNumber)
    {
        Console.WriteLine("Bad luck, here's a hint, try a LOWER number\n"); //If wrong guess give user hint
    }
} 

